%%{init: { 'theme': 'base', 'themeVariables': {
    'darkMode': true,
    'background': '#000000',
    'fontFamily': 'arial',
    'primaryColor': '#ff9e1f',
    'primaryTextColor': '#fff',
    'lineColor': '#ff9e1f',
    'textColor': '#fff',
    'mainBkg': '#111111',
    'git0': '#ff9e1f',
    'git1': '#6e9fff',
    'git2': '#ff4444',
    'gitBranchLabel0': '#fff',
    'gitBranchLabel1': '#fff',
    'gitBranchLabel2': '#fff',
    'commitLabelColor': '#fff',
    'commitLabelBackground': '#111111',
    'tagLabelColor': '#fff',
    'tagLabelBackground': '#3a1010',
    'tagLabelBorder': '#ff4444'
}}}%%

gitGraph LR:
    commit id: "v5.17"
    branch net
    commit id: "a1"
    commit id: "a2"
    commit id: "a3"
    checkout main
    branch mm
    commit id: "b1"
    commit id: "b2" type: HIGHLIGHT
    checkout main
    merge net
    merge mm tag: "v5.18"
    commit id: "..."
