%%{init: { 'theme': 'base', 'themeVariables': {
    'darkMode': true,
    'background': '#000000',
    'fontFamily': 'verdana',
    'primaryColor': '#ff9e1f',
    'primaryTextColor': '#fff',
    'lineColor': '#ff9e1f',
    'textColor': '#fff',
    'mainBkg': '#111111',
    'git0': '#ff9e1f',
    'git1': '#ff4444',
    'gitBranchLabel0': '#fff',
    'commitLabelColor': '#fff',
    'commitLabelBackground': '#111111',
    'tagLabelColor': '#fff',
    'tagLabelBackground': '#3a1010',
    'tagLabelBorder': '#ff4444'
}}}%%

gitGraph LR:
    commit id: "v5.17" tag: "good"
    commit id: "56a4d67" type: HIGHLIGHT
    commit id: "v5.18" tag: "баг здесь"
    commit id: "5.19"
    commit id: "6.1"
    commit id: "6.5"
    commit id: "6.8"
    commit id: "bc2ff4c" type: HIGHLIGHT
    commit id: "v6.9" tag: "фикс"
