%%{init: { 'theme': 'dark', 'themeVariables': {
    'cScale0': '#3a2a1e',
    'cScaleLabel0': '#FFD02F'
}}}%%

timeline
    title Расследование
    section Декабрь-Январь
        30 дек
            : segfault
            : безумная гипотеза
        7 янв
            : пинг-понг
